name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 0 */6 * *' # Ejecuta una vez cada 6 días a la medianoche UTC
  workflow_dispatch: # Permite ejecutar manualmente el workflow desde la interfaz de GitHub

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
    - name: Add random delay
      run: |
        # Generar un número aleatorio de segundos entre 0 y 43200 (12 horas)
        RANDOM_DELAY=$(( RANDOM % 43200 ))
        echo "Esperando $RANDOM_DELAY segundos antes de enviar la solicitud..."
        sleep $RANDOM_DELAY
    - name: Send request to Supabase API
      run: |
        curl -X GET "https://kcwfwezswjozqsshzger.supabase.co/rest/v1/persona" \
        -H "apikey: ${{ secrets.SUPABASE_API_KEY }}"
